version: '3.9'
services:
  db:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-tier
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app-tier
  app:
    build: . 
    ports:
      - "8080:8080"
    networks:
      - app-tier
    depends_on:
      - db
    links:
      - db:db 
networks:
    app-tier:
          driver: bridge
      
